@startuml
actor Client
actor Administrateur
actor "Système de paiement" as SystemePaiement

usecase "Consulter le catalogue" as UC1
usecase "Ajouter produit au panier" as UC2
usecase "Valider le panier" as UC3
usecase "Créer commande" as UC4
usecase "Consulter commandes" as UC5
usecase "Modifier informations personnelles" as UC6

usecase "Gérer produits" as UC7
usecase "Gérer catégories et sous-catégories" as UC8
usecase "Consulter toutes les commandes" as UC9
usecase "Consulter toutes les factures" as UC10

usecase "Traiter paiement" as UC11

Client --> UC1
Client --> UC2
Client --> UC3
Client --> UC4
Client --> UC5
Client --> UC6

Administrateur --> UC7
Administrateur --> UC8
Administrateur --> UC9
Administrateur --> UC10

UC4 --> UC11 : include

SystemePaiement --> UC11
@enduml
