@startuml
class Client {
    - clientId : int
    - nom : String
    - prenom : String
    - adresse : String
    - password : String
    - typeClient : bool
    - coefficient : float
}

class Produit {
    - produitId : int
    - libelle : String
    - description : String
    - prixAchat : float
    - photo : String
    - rubrique : String
    - sousRubrique : String
}

class Commande {
    - commandeId : int
    - dateCommande : Date
    - montantTotal : decimal
    - statut : String
    - clientId : int
}

class Facture {
    - factureId : int
    - commandeId : int
    - montant : decimal
    - dateEmission : Date
}

class Categorie {
    - categorieId : int
    - produits : List<Produit>
}

class SsCategorie{
    -sscategorieId : int
    -produits : List<Produit>
}

Client "1" --> "0..*" Commande
Commande "1" --> "1" Facture
Catalogue "1" --> "0..*" Produit
SsCategorie "1"-->"0..*"Categorie
@enduml