controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

app_cgu:
    path: /cgu
    controller: App\Controller\CguController::cgu

app_politique:
    path: /politique
    controller: App\Controller\PoliMentionController::politique

app_mentions:
    path: /mentions
    controller: App\Controller\PoliMentionController::mentions

app_registration:
    path: /register
    controller: App\Controller\RegistrationController::register

Role_dashboard:
    path: /Role/dashboard
    controller: App\Controller\RoleController::dashboard
    methods: ['GET', 'POST']

product_detail:
    path: /produit/{id}
    controller: App\Controller\ProductController::show
    methods: GET

get_products:
    path: /get-products
    controller: App\Controller\CatalogueController::getProducts

get_categories:
    path: /get-categories
    controller: App\Controller\CatalogueController::getCategories

app_categories:
    path: /categories
    controller: App\Controller\CatalogueController::categories
    methods: GET

modifier_produit:
    path: /modifier/{id}
    controller: App\Controller\RoleController::modifierProduit
    methods: ['GET', 'POST']

app_commander:
    path: /commander
    controller: App\Controller\CommandeController::commander
    methods: [POST]

app_commande_confirmation:
    path: /commande/confirmation/{id}
    controller: App\Controller\CommandeController::confirmation

app_historique_commandes:
    path: /historique-commandes
    controller: App\Controller\RoleController::historiqueCommandes
    methods: GET

app_reset:
    path: /reset
    controller: App\Controller\ResetController::index
    methods: [GET, POST]

change_password:
    path: /change/{token}
    controller: App\Controller\ResetController::change_password
    methods: [GET, POST]
