@startuml
start

:Se connecter;
:Rechercher produit;
:Afficher détails produit;

if (Produit trouvé ?) then (oui)
  :Ajouter produit au panier;
else (non)
  :Afficher message d'erreur;
  stop
endif

:Passer commande;

:Enregistrer commande;
:Enregistrer produits de la commande;

:Préparer livraison;
:Enregistrer livraison;

:Envoyer confirmation au client;

stop
@enduml
