@startuml
actor Client
actor Admin
actor Commercial

usecase "Se connecter" as UC1
usecase "Rechercher produit" as UC2
usecase "Ajouter au panier" as UC3
usecase "Passer commande" as UC4
usecase "Gérer les commandes" as UC5
usecase "Gérer les produits" as UC6
usecase "Gérer les clients" as UC7
usecase "Gérer les fournisseurs" as UC8
usecase "Gérer les erreurs du site" as UC9
usecase "Gérer le panneau d'administration" as UC10

Client -- UC1
Client -- UC2
Client -- UC3
Client -- UC4

Commercial -- UC5
Commercial -- UC6
Commercial -- UC7
Commercial -- UC8

Admin -- UC9
Admin -- UC10
@enduml
