@startuml

class Categorie {
  int id
  int id_parent
  String nom
  String image
}

class Client {
  int id
  int id_commercial
  String nom
  String prenom
  String adresse_mail
  String adresse
  String telephone
  String role
  String mot_de_passe
  boolean type_client
  double coefficient
  double reduc_pro
  String jeton
}

class Commande {
  int id
  int id_client
  Date date_debut_commande
  String nom_commande
  String statut
  double montant_tot
  Date date_emission
  double montant
  String adresse_livraison
  String adresse_facturation
}

class Commande_Produit {
  int id
  int id_commande
  int id_produit
  int quantite
}

class Commercial {
  int id
  String nom
  String role
  String adresse_mail
  String mot_de_passe
}

class Fournisseur {
  int id
  String nom
  String ref_fournisseur
}

class Livraison {
  int id
  int id_commande
  Date date_envoi
  Date date_reception
}

class Messenger_Messages {
  long id
  String corps
  String en_tetes
  String nom_file_attente
  Date
